# TransPose模型训练配置文件

# 基本配置
model_name: "TransPose_IMU"
tensorboard_project_name: "imu_transpose"  # TensorBoard项目名称
model_type: "TransPose"  # 模型类型：使用TransPose
device: "cuda:0"  # 主GPU设备
gpus: [0]  # 使用的GPU编号列表，支持多卡训练
           # 单卡训练: [0] 
           # 双卡训练: [0, 1]
save_dir: "outputs/TransPose"  # 模型保存路径
use_tensorboard: True  # 是否使用tensorboard记录训练过程
use_multi_gpu: True  # 是否启用多GPU训练（当gpus列表长度>1时自动启用）
bm_path: body_models/smplh/male/model.npz
use_transpose_model: True

# 全局默认训练超参数（用作阶段超参数的兜底值）
epoch: 850  # 训练轮数
batch_size: 50  # 批大小（多GPU时会自动分配到各GPU）
lr: 0.0004  # 学习率（多GPU时会自动按GPU数量线性缩放）
weight_decay: 0.0001  # 权重衰减
milestones: []  # 学习率调整节点
gamma: 0.2  # 学习率衰减系数
seed: 42  # 随机种子
num_workers: 12  # 数据加载线程数（多GPU时建议增加）
hidden_dim_multiplier: 1  # 隐藏层维度乘数

# 特征维度配置
num_human_imus: 6  # 人体IMU数量
imu_dim: 9  # 每个IMU的特征维度（加速度向量3维 + 6D旋转表示6维）
num_joints: 22  # SMPL模型关节数量
joint_dim: 6  # 使用6D旋转表示
vel_scale: 3

# 物体静止相关参数
obj_imu_change_threshold: 0.1
obj_contact_threshold: 0.3
obj_rot_weight: 0.5

# ContactAwareLoss相关参数
use_contact_aware_loss: False  # 是否使用ContactAwareLoss
contact_distance: 0.1  # 目标接触距离 10cm
contact_ramp_up_steps: 10000  # 基础损失3000步后达到全权重

# ContactAwareLoss内部权重
contact_loss_weights:
  contact_distance: 1.0      # 距离一致性权重
  contact_velocity: 0.5      # 速度一致性权重
  approach_smoothness: 0.3   # 接近平滑性权重
  contact_consistency: 0.2   # 接触状态一致性权重

# 手部接触相关参数
hand_contact_distance: 0.1   # 10cm目标距离

# 分阶段训练配置
staged_training:
  enabled: True  # 是否启用分阶段训练
  
  # 模块化训练配置
  modular_training:
    enabled: True  # 是否启用模块化训练
    start_from_stage: "human_pose"  # 从哪个阶段开始训练，可选: "velocity_contact", "human_pose", "object_trans_hoi", "object_trans", "joint_training"
    pretrained_modules:  # 预训练模块路径
      velocity_contact: "outputs/TransPose/transpose_08200259/modules/velocity_contact_best.pt"
      human_pose: "outputs/TransPose/transpose_09241736/modules/human_pose_best.pt"
      object_trans: "outputs/TransPose/transpose_09241736/modules/object_trans_best.pt"
  
  # 正常训练阶段配置（每个阶段都有独立的超参数）
  stages:
    - name: "velocity_contact"
      epochs: 200  # 阶段时长（epoch 数）
      modules: ["velocity_contact"]
      datasets: ["omomo"]
      batch_size: 50
      milestones: [50, 100, 140, 170, 190]
      gamma: 0.2
    - name: "human_pose"
      epochs: 300  # 阶段时长（epoch 数）
      modules: ["human_pose"]
      datasets: ["omomo"]
      batch_size: 40
      milestones: [100, 200, 300]
      gamma: 0.2
    - name: "object_trans_hoi"
      epochs: 300  # 阶段时长（epoch 数）
      modules: ["object_trans"]
      datasets: ["hoi"]
      batch_size: 50
      milestones: [100, 200, 300]
      gamma: 0.2
    - name: "object_trans"
      epochs: 300  # 阶段时长（epoch 数）
      modules: ["object_trans"]
      datasets: ["omomo"]
      batch_size: 50
      milestones: [100, 200, 300]
      gamma: 0.2
    - name: "joint_training"
      epochs: 300
      modules: ["human_pose", "object_trans"]
      datasets: ["omomo"]
      batch_size: 50
      milestones: [80, 120, 160, 200, 240, 280]
      gamma: 0.2

  debug_stages:
  - name: "velocity_contact"
    epochs: 11  # 阶段时长（epoch 数）
    modules: ["velocity_contact"]  # 激活的模块
    datasets: ["omomo"]  # 使用的数据集类型：amass、omomo、mixed
  - name: "human_pose"  
    epochs: 10  # 阶段时长（epoch 数）
    modules: ["human_pose"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集
  - name: "object_trans_hoi"
    epochs: 10  # 阶段时长（epoch 数）
    modules: ["object_trans"]  # 激活的模块
    datasets: ["hoi"]  # 只使用OMOMO数据集
  - name: "object_trans"
    epochs: 10  # 阶段时长（epoch 数）
    modules: ["object_trans"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集（有物体）
  - name: "joint_training"
    epochs: 10  
    modules: ["human_pose", "object_trans"]  # 激活的模块
    datasets: ["omomo"]  # 只使用OMOMO数据集（有物体）

# 数据集配置
datasets:
  amass:
    train_path: "processed_amass_data_0703/train"
    test_path: "processed_amass_data_0703/test"
    debug_path: "processed_amass_data_0703/debug"  # AMASS调试数据路径
  omomo:
    train_path: "processed_data_0701/train"
    test_path: "processed_data_0701/test"
    debug_path: "processed_data_0701/debug"  # OMOMO调试数据路径
  hoi:
    train_path: "processed_hoi_data_0803/train"
    test_path: "processed_hoi_data_0803/test"
    debug_path: "processed_hoi_data_0803/debug"

loss_weights: 
  {
    'obj_vel': 1, 'leaf_vel': 1, 'hand_contact': 1,
    'rot': 10, 'leaf_pos': 10, 'full_pos': 10,
    'lhand_obj_direction': 0.1, 'rhand_obj_direction': 0.1, 'lhand_lb': 0.1, 'rhand_lb': 0.1,
    'obj_trans_fused': 1, 'hoi_error_r': 0.2, 'hoi_error_l': 0.2, 'obj_vel_cons': 1, 'obj_acc_cons': 0.01
  }

# 训练窗口配置
train:
  window: 120  # 训练时使用的时间窗口长度
  # window_stride: 60  # 训练时窗口步长
  normalize: True  # 是否归一化数据
  data_path: 
    "processed_data_0701/train"  # 训练数据路径1（传统模式使用）
  debug_data_path: "processed_data_0701/debug"  # 调试数据路径

# 测试窗口配置
test:
  window: 120  # 测试时使用的时间窗口长度
  # window_stride: 120  # 测试时窗口步长
  normalize: True  # 是否归一化数据
  data_path: 
    "processed_data_0701/test"  # 测试数据路径1（传统模式使用）